# ─────────────────────────────────────
# Linxdot MQTT Forwarder Configuration
# 適用架構：ChirpStack Concentratord + MQTT Cloud Server
# ─────────────────────────────────────

# ───── 日誌設定 ─────
[logging]
level = "INFO"
log_to_syslog = true

# ───── MQTT 連線設定 ─────
[mqtt]
# MQTT broker 位址，支援 tcp://, ssl://, ws:// 等格式
server = "tcp://13.55.159.24:1883"

# MQTT topic prefix
# 實際 topics 將會是：
#   as923/gateway/<GatewayID>/event/<EventType>
#   as923/gateway/<GatewayID>/state/<StateType>
#   as923/gateway/<GatewayID>/command/<Command>
topic_prefix = "as923"

# 是否使用 JSON 格式傳輸資料（建議保持 false，除非為 debug 用）
json = false

# MQTT QoS（0~2）：越高可靠性越強，但效能越差
qos = 0

# clean_session 設定為 false 表示 broker 可保留未處理訊息
clean_session = false

# 留空表示自動產生 client_id
client_id = ""

# 若需要 TLS / 帳密可加上以下選項（目前為匿名）
username = ""
password = ""
ca_cert = ""
tls_cert = ""
tls_key = ""

# ───── 資料來源後端 ─────
[backend]
# 資料來源：此處設定為使用 chirpstack-concentratord
enabled = "concentratord"

  [backend.filters]
  # 僅上送 CRC 正確的封包（建議）
  forward_crc_ok = true
  forward_crc_invalid = false
  forward_crc_missing = false

  # 不進行 DevAddr / JoinEUI 過濾
  dev_addr_prefixes = []
  join_eui_prefixes = []

# ───── 與 Concentratord 的 IPC 通訊路徑 ─────
[backend.concentratord]
event_url = "ipc:///tmp/concentratord_event"
command_url = "ipc:///tmp/concentratord_command"

# ───── Metadata（可留空）─────
[metadata.static]
# serial_number = "LD1002-0001"

[metadata.commands]
# datetime = ["date", "-R"]

# ───── 支援遠端命令功能（非必要）─────
[commands]
# reboot = ["/sbin/reboot"]

