# Beacon configuration.
#
# This requires a gateway with GPS / GNSS.
[gateway.beacon]

# Compulsory RFU size.
compulsory_rfu_size=2

# Beacon frequency / frequencies (Hz).
frequencies=[
  923200000,
  923400000,
  923600000,
  923800000,
  924000000,
  924200000,
  924400000,
  924600000,
]

# Bandwidth (Hz).
bandwidth=125000

# Spreading factor.
spreading_factor=9

# TX power.
tx_power=14
