#!/bin/sh /etc/rc.common

# ───────────────────────────────────────────────
# OpenWrt init.d 服務腳本
# Module: ChirpStack UDP Forwarder (Linxdot)
# 不使用 run script，直接啟動 binary
# ───────────────────────────────────────────────

START=99
USE_PROCD=1

start_service() {
    logger -t "chirpstack_udp_forwarder" "Starting ChirpStack UDP Forwarder..."

    procd_open_instance
    procd_set_param command /opt/awesome_linxdot/awesome_software/chirpstack_udp_forwarder/chirpstack_udp_forwarder_binary/chirpstack_udp_forwarder -c /opt/awesome_linxdot/awesome_software/chirpstack_udp_forwarder/chirpstack_udp_forwarder_binary/chirpstack_udp_forwarder.toml
    procd_set_param respawn 3600 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
